### ISSUE TITLE
Make object as a valid type in schema fields

### ISSUE THREAD

**Issue by NiranjanAP** [cord-network/cord.js#103]
## Description
When a data is represented digitally, it can be of complex type, not just a basic 'string', number, date, boolean format. If there is a complex data type, it can then be represented as an 'object' in schema, which can be handled during parsing of the data during IDocument (Verifiable document) format.

## Goals

- [ ] Allow usage of a complex type

## Expected Outcome
We should be able to store a complex type.

## Acceptance Criteria
NA

## Implementation Details
NA

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts 

## Complexity
Medium

## Category
Feature

## Sub Category
Technical Debt

**Comment by KDwevedi** [comment]
comment

**Comment by KDwevedi** [comment]
comment

**Comment by KDwevedi** [comment]
comment

**Comment by heh155** [comment]
I want to contribute about this issue 103. 
I am really interested for a contribution.i am new to this if possible can I get a guidance.
@NiranjanAP @amarts

**Comment by NiranjanAP** [comment]
Sure, pls start by making yourself familiar with the steps in running the demo script and the code
- Run the CORD instance locally, refer https://github.com/dhiway/cord/blob/develop/README.md
- Run cord.js demo script - https://github.com/dhiway/cord.js/blob/develop/README.md, npx tsx demo/src/func-test.ts
- Go through the code of demoscript to understand the steps involved in creating a verifiable credentials

**Comment by Gmin2** [comment]
> Sure, pls start by making yourself familiar with the steps in running the demo script and the code
> 
> * Run the CORD instance locally, refer https://github.com/dhiway/cord/blob/develop/README.md
> * Run cord.js demo script - https://github.com/dhiway/cord.js/blob/develop/README.md, npx tsx demo/src/func-test.ts
> * Go through the code of demoscript to understand the steps involved in creating a verifiable credentials

Hey @NiranjanAP i have done the following steps can i work on this!

**Comment by NiranjanAP** [comment]
@Min2who  this is already implemented as part of a refactor, will be closing this now. Thanks
