### ISSUE TITLE
Provide 'update' method for stream contents

### ISSUE THREAD

**Issue by NiranjanAP** [cord-network/cord.js#105]
## Description
Today, we have stream.create() and stream.revoke() methods added in cord.js SDK. We need to build proper interfaces and methods for stream.update() extrinsic, so we can get started with full fledged integration with current studio and any other tools like sunbird RC.

## Goals
- [ ] Build interfaces and methods for stream.update()
- [ ] Integrate the new interface in demo.ts

## Expected Outcome
new module updateStream creation and integration with demo.ts script

## Acceptance Criteria
demo.ts should continue to work with the changes

## Implementation Details
- [ ] create a new file demo/src/utils/updateStream.ts
- [ ] make call to api.tx.stream.update()
- [ ] import updateStream.ts into demo.ts

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
Blockchain

## Tech Skills Needed
Rust

## Mentor(s)
@amarts @NiranjanAP 

## Complexity
Low

## Category
Feature

## Sub Category
Refactoring

**Comment by heh155** [comment]
Kindly assign me this issue 105 . I want to contribute. If possible I need some guidance
. I am really interested to contribute @NiranjanAP @amarts

**Comment by NiranjanAP** [comment]
This is outdated issue now because of a major restructuring we did, will be closing this. Thanks for checking on it

**Comment by NiranjanAP** [comment]
Issue is not longer applicable because of a major restructure, hence closed
