### ISSUE TITLE
[C4GT] Support Array fields in selective disclosure

### ISSUE THREAD

**Issue by amarts** [cord-network/cord.js#110]
## Description
A content in a VC (Verifiable Credential) can be an array (like string, number, boolean or object). We are adding support for `object` type through #109  similarly we need to add support to individual array elements to be available separately in content-hash.

## Goals

- [ ] Allow usage of a array type in a Verifiable Credential's schema and thus VC content.

## Expected Outcome
We should be able to issue and verify a VC with array element.

## Acceptance Criteria
NA

## Implementation Details
NA

## Mockups / Wireframes
NA

---- 

## Product Name
CORD

## Organization Name
Dhiway

## Domain
VC, SDK, 

## Tech Skills Needed
TypeScript

## Mentor(s)
@amarts / @NiranjanAP 

## Complexity
[Low]

## Category
[Feature]

## Sub Category
[API], [Technical Debt], [Beginner friendly], [Research]

**Comment by SoumyadipYT-OSS** [comment]
As the requirements skill set criteria is matching with my skill set, it would be a great chance for me to learn new real-world problems and gaining new knowledge from this experience. And yeah, I am interested in this project.

**Comment by MayaSatishRao** [comment]
@amarts @NiranjanAP I want to contribute to this issue. I did not understand the issue completely. Can you help me on this?

**Comment by NiranjanAP** [comment]
@SoumyadipYT-OSS @MayaSatishRao  this piece is undergoing some major changes, you can ignore this issue.
