### ISSUE TITLE
Build errors encountered after augment-api update

### ISSUE THREAD

**Issue by belyrs** [cord-network/cord.js#127]
➤ YN0000: src/interfaces/augment-types.ts(328,5): error TS2300: Duplicate identifier 'Data'.
➤ YN0000: src/interfaces/augment-types.ts(329,5): error TS2300: Duplicate identifier 'Data'.
➤ YN0000: src/interfaces/extraDefs/types.ts(21,34): error TS2304: Cannot find name 'PalletDidServiceEndpointsDidEndpoint'.
➤ YN0000: src/interfaces/extraDefs/types.ts(21,34): error TS4033: Property 'serviceEndpoints' of exported interface has or is using private name 'PalletDidServiceEndpointsDidEndpoint'.
➤ YN0000: src/interfaces/extraDefs/types.ts(22,21): error TS2304: Cannot find name 'PalletDidDidDetails'.
➤ YN0000: src/interfaces/extraDefs/types.ts(22,21): error TS4033: Property 'details' of exported interface has or is using private name 'PalletDidDidDetails'.

reference to commit - c08c2d566585939731838b5ee48a8959ec1a6cf9

**Comment by belyrs** [comment]
@smohan-dw, Can I please get some suggestions?

**Comment by smohan-dw** [comment]
Why are we updating augment-api. The latest chain spec based changes are already updated.

**Comment by belyrs** [comment]
> Why are we updating augment-api. The latest chain spec based changes are already updated.

Was this update done after merging the scoring pallet to the develop?

**Comment by belyrs** [comment]
Because, I've noticed that the scoring pallet was merged into the codebase yesterday, while the update of cord.js took place five days ago

**Comment by smohan-dw** [comment]
this is fixed in develop
