### ISSUE TITLE
Add Support for DID Creation and Retrieval in SDK

### ISSUE THREAD

**Issue by belyrs** [cord-network/cord.js#175]
**Issue:**
All write operations in CORD are performed through DID calls. However, the createDid method, which is essential for creating DIDs, is not included in the SDK. This presents a limitation as developers are unable to utilize the SDK for DID creation despite the pivotal role DIDs play within the system.

Typically, developers generate a mnemonic and a corresponding DID, storing only the mnemonic for future reference. It is imperative for the SDK to include functionality for retrieving the DID using the mnemonic directly. Presently, developers must manually create a custom function to extract the DID from the blockchain by providing the mnemonic as input.

**Proposal:**
To enhance the functionality and usability of the SDK, it's crucial to add support for both DID creation and retrieval. This would streamline the development process and align with the common practice where developers generate a mnemonic and DID, storing only the mnemonic while relying on the SDK to handle DID retrieval.

**Expected Behavior:**

1. Addition of `createDid` method within the SDK, enabling developers to programmatically generate DIDs.
2. Implementation of `fetchDidFromMnemonic` method to retrieve DIDs using mnemonics, simplifying the process for developers.

**Comment by amarts** [comment]
Good find, and needed. Meantime, consider providing 'serviceEndPoint' as an option, and can be of any choice of key value user chooses.
