### ISSUE TITLE
Improve SDK Behavior for Duplicate Statement Anchoring

### ISSUE THREAD

**Issue by belyrs** [cord-network/cord.js#177]
**Description:**
When attempting to anchor a statement that is already present on the chain using the SDK, the current behaviour is confusing. The SDK returns the identifier without errors and no events are observed on the chain. It becomes perplexing because, while the terminal indicates that the dispatch call has been executed, there are no corresponding events observable on the chain. Consequently, one is left pondering why no error is displayed or why the event is absent on the chain, despite the SDK indicating successful execution without errors.

**Proposed Fix:**
If the statement is already anchored on the chain, the SDK should throw an error indicating "The statement already exists" and should also return the identifier for reference.

**Comment by vatsa287** [comment]
Closing as completed with #178.
