### ISSUE TITLE
Move `signAndSubmitTx` out of the function `dispatchRegisterToChain` & `dispatchRevokeToChain`

### ISSUE THREAD

**Issue by Vikastc** [cord-network/cord.js#180]
**Issue:**
The `authorizeBatch()` function currently accepts an array of Extrinsic objects as its argument. However, when utilizing `dispatchRegisterToChain()`, it submits a single transaction directly to the chain.

**Requirement**:
For bulk uploads or revocations of records in the studio.

**Solution**:
To address this, consider removing the `signAndSubmitTx()` function from within `dispatchRegisterToChain()` and instead have it return only the extrinsic. The same has to be done for `dispatchRevokeToChain()`

**Comment by amarts** [comment]
Suggestion: considering the name of method is dispatchToChain(), can we move everything before sign and submit to `prepareExtrinsic()` method, which also can be exported from the SDK, and the dispatch also can get the extrinsic from same method.

**Comment by Vikastc** [comment]
That will suffice
