### ISSUE TITLE
`api.tx.utility.batchAll()` error occurrence

### ISSUE THREAD

**Issue by Vikastc** [cord-network/cord.js#186]
**Issue:**
Encountering an error "The DID operation nonce does not match the current DID nonce + 1" when using `api.tx.utility.batchAll()`.

**Requirement**:
For bulk uploads or revocations of records in the studio.

**Comment by amarts** [comment]
@Vikastc @vatsa287 we need to revert above PR, and instead consider using [`authorizeBatch`](https://github.com/dhiway/cord.js/blob/develop/packages/did/src/DidDetails/FullDidDetails.ts#L195) instead of 'authorizeTx' of Did in dispatch methods. We need to experiment and plan to use it properly.

**Comment by vatsa287** [comment]
@amarts Ack.

**Comment by Vikastc** [comment]
Got it
