### ISSUE TITLE
[C4GT] ChainSpace: Separate preparation of create chainspace extrinsic from chain dispatch

### ISSUE THREAD

**Issue by vatsa287** [cord-network/cord.js#197]
## Description
Separate chain-space creation preparation and dispatch of extrinsic to chain. This would help when bulk transaction takes place so we just prepare all the required extrinsics and then execute these transaction in batches by dumping them into a promise using 
a batch sign & submit utility ex, `authorizeBatch` which can take array of extrinsics, instead of just one.

## Goals

- [ ] Creation of new export function named `prepareCreateSpaceExtrinsic()`
- [ ] Integration of above method into existing `dispatchToChain()`

## Implementation Details
Developers/Contributors can refer to example PRs: #188, #182

---- 

## Product Name
CORD.JS

## Organization Name
Dhiway

## Domain
Blockchain, SDK Development, API

## Tech Skills Needed
Typescript 

## Mentor(s)
@amarts @NiranjanAP @vatsa287 @adi-a11y 

## Complexity
[Low]

## Category
[Performance Improvement], [Feature]

## Sub Category
 [API], [Refactoring], [Backend], [Beginner friendly]

**Comment by PayalKumari10** [comment]
@vatsa287  Please submit this issue to me, I will try my best.

**Comment by zeel991** [comment]
> @vatsa287  Please submit this issue to me, I will try my best.

Hey Payal ! You can start to work on this issue and raise your PR , if everything seems right , you'll be assigned

**Comment by HimanshuGarg5480** [comment]
Hey @vatsa287 @zeel991 @PayalKumari10 , I'm new to open source. Could you please guide me on setting up the repository?

**Comment by hardiksharma11** [comment]
Hi @vatsa287 if it's still open I would like to work on it. If @PayalKumari10 is continuing she can go on ...
