### ISSUE TITLE
[C4GT] ChainSpace: Separate preparation of UpdateTxCapacityToChain from dispatch

### ISSUE THREAD

**Issue by vatsa287** [cord-network/cord.js#204]
## Description
Separate UpdateTxCapacityToChain preparation and dispatch of extrinsic to chain. This would help when bulk transaction takes place so we just prepare all the required extrinsics and then execute these transaction in batches by dumping them into a promise using 
a batch sign & submit utility ex, `authorizeBatch` which can take array of extrinsics, instead of just one.

## Goals

- [ ] Creation of new export function named `prepareUpdateTxCapacityExtrinsic()`, which will contain `updateTransactionCapacitySub()` and `Did.AuthorizeTx()`. 
- [ ] Integration of above method into existing `dispatchUpdateTxCapacityToChain()`

## Implementation Details
Developers/Contributors can refer to example PRs: #188, #182

---- 

## Product Name
CORD.JS

## Organization Name
Dhiway

## Domain
Blockchain, SDK Development, API

## Tech Skills Needed
Typescript 

## Mentor(s)
@amarts @vatsa287

## Complexity
[Low]

## Category
[Performance Improvement], [Feature]

## Sub Category
 [API], [Refactoring], [Backend], [Beginner friendly]

**Comment by Aarsh30** [comment]
i would like to work on this issues can u assign it to me

**Comment by nitin14gupta** [comment]
i would like to work on this issues can u assign it to me, this align with my expertise @vatsa287

**Comment by vatsa287** [comment]
@nitin14gupta This issue has been closed.
