### ISSUE TITLE
Yarn complains about missing NPM token 

### ISSUE THREAD

**Issue by smohan-dw** [cord-network/cord.js#33]
Usage Error: Environment variable not found (NPM_TOKEN) in /Users/smohan/devel/smohan/ondc/cord.js/.yarnrc.yml (in /Users/smohan/devel/smohan/ondc/cord.js/.yarnrc.yml)

**Comment by amarts** [comment]
Thinking more about it, that line with NPM_TOKEN is required only for publish. Let's remove it, and will add it in CI scripts or while manually publishing.

**Comment by amarts** [comment]
1f2a73aa0c4973bdccfd9f9038367eefc03dcf4a fixed the issue.
