### ISSUE TITLE
make develop the default branch

### ISSUE THREAD

**Issue by smohan-dw** [cord-network/cord.js#66]
Defaulting to the main often ends up with developers starting with the wrong branch

**Comment by amarts** [comment]
@smohan-dw `develop` is the default branch in cord.js right now (since some time now). Details in [Settings](https://github.com/dhiway/cord.js/settings) and [Branches](https://github.com/dhiway/cord.js/branches) page

**Comment by smohan-dw** [comment]
My bad. it was main on the fork I created
