### ISSUE TITLE
[C4GT] make 'object' as a valid 'type' in schema fields

### ISSUE THREAD

**Issue by amarts** [cord-network/cord.js#86]
## What is this enhancement about?

When a data is represented digitally, it can be of complex type, not just a basic 'string', number, date, boolean format. If there is a complex data type, it can then be represented as an 'object' in schema, which can be handled during parsing of the data during `IDocument` (Verifiable document) format.

## How to test it?

Add a schema with 'object' type of field, for example below sample:

```
{ .... 
   "properties": {
      "address": {
          "type": "object",
           "properties": {
              "street": ...,
              "pincode": ...,
              "state": ...,
              "district": ..., 
          }
       }
   }
  ...
}
```

and then use the data similarly. 

## Things to look out for

* How will `contentHashes` part of `IDocument` (or VC proof) be structured if its object?

**Comment by NiranjanAP** [comment]
create a different one with right formatting for C4GT
