### ISSUE TITLE
[C4GT] provide 'update' method for stream contents

### ISSUE THREAD

**Issue by amarts** [cord-network/cord.js#87]
## What is this enhancement about?

Today, we have `stream.create()` and `stream.revoke()` methods added in cord.js SDK. We need to build proper interfaces and methods for `stream.update()` extrinsic, so we can get started with full fledged integration with current studio and any other tools like sunbird RC.

## How to test?

Enhance `yarn demo` to perform stream.update, and make sure we see stream.updated event on chain using explorer UI.

## What are the things to consider?

* `content` module will have to get a proper 'update()' method too, which should be passed for stream module.

**Comment by NiranjanAP** [comment]
Created another issue with proper formatting needed for displaying on C4GT portal
